baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'Angad Muthyala - Portfolio'

[params]
  author = 'Angad Muthyala'
  description = 'Computer Science Student | Backend Developer | AI Enthusiast'
  email = 'angadmuthyala@gmail.com'
  phone = '+91-8779263718'
  location = 'Mumbai, India'
  github = 'https://github.com/AngadVM'
  linkedin = 'https://www.linkedin.com/in/angad-muthyala/'

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 2

[[menu.main]]
  name = 'Projects'
  url = '/projects/'
  weight = 3

[[menu.main]]
  name = 'Community'
  url = '/community/'
  weight = 4

[[menu.main]]
  name = 'Contact'
  url = '/contact/'
  weight = 5
